name: conv_onet
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - cython=0.29.34
  - h5py=3.8.0
  - imageio=2.27.0
  - numpy=1.24.2
  - matplotlib=3.7.1
  - pandas=2.0.0
  - pillow=9.4.0
  - plyfile=0.8.1
  - pyembree=0.1.6
  - pykdtree=1.3.7.post0
  - pytest=7.2.2
  - python=3.10
  - pytorch=2.0.0
  - pytorch-scatter=2.1.1
  - pyyaml=6.0
  - scikit-image=0.20.0
  - scipy=1.10.1
  - tensorboardx=2.5.1
  - torchvision=0.15.0
  - tqdm=4.65.0
  - trimesh=3.21.4
